name: Pylint

on: [pull_request]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: codecov/codecov-action@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install flake8_docstrings
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs` --disable=missing-docstring
    - name: Run tests
      run: |
        python test.py 
